import { resolve } from 'node:path'
import { isSafeWorkflowId } from './ids.ts'
import { STEP_META } from './stages.ts'
import { isSupportedWorkflowIntent } from './supportPolicy.ts'
import type { RunInput, StepId } from './types.ts'

const MODULES = new Set(['ubase', 'cdma', 'udma', 'ummu', 'ubus'])
const MODES = new Set(['dev', 'full', 'explore'])
const STEP_IDS = new Set(Object.keys(STEP_META))
export const MAX_REQUIREMENT_LENGTH = 20_000
const MAX_RESPONSE_LENGTH = 20_000

export type ValidationResult<T> =
  | { ok: true; value: T }
  | { ok: false; status: number; error: string }

function reject(status: number, error: string): ValidationResult<never> {
  return { ok: false, status, error }
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}

export function validateRequirement(value: unknown): ValidationResult<string> {
  if (typeof value !== 'string') return reject(400, 'requirement is required')
  const requirement = value.trim()
  if (requirement === '') return reject(400, 'requirement is required')
  if (requirement.length > MAX_REQUIREMENT_LENGTH) return reject(413, 'requirement is too large')
  return { ok: true, value: requirement }
}

function samePath(left: string, right: string): boolean {
  const a = resolve(left)
  const b = resolve(right)
  return process.platform === 'win32' ? a.toLowerCase() === b.toLowerCase() : a === b
}

export function validateLaunchBody(body: unknown, configuredRepo: string): ValidationResult<RunInput> {
  if (!isRecord(body)) return reject(400, 'JSON object body is required')
  if ('runId' in body) return reject(400, 'runId is generated by the host')

  if (body.repoPath !== undefined) {
    if (typeof body.repoPath !== 'string' || !samePath(body.repoPath.trim(), configuredRepo)) {
      return reject(403, 'workspace override is not allowed')
    }
  }

  const validatedRequirement = validateRequirement(body.requirement)
  if (!validatedRequirement.ok) return validatedRequirement
  const requirement = validatedRequirement.value

  const mode = body.mode ?? 'dev'
  if (typeof mode !== 'string' || !MODES.has(mode)) return reject(400, 'invalid workflow mode')
  if (typeof body.module !== 'string' || !MODULES.has(body.module)) return reject(400, 'module is required')
  if (body.changeId !== undefined && !isSafeWorkflowId(body.changeId)) return reject(400, 'invalid changeId')
  if (body.sessionId !== undefined && (
    typeof body.sessionId !== 'string' || body.sessionId.trim() === '' || body.sessionId.length > 256
  )) return reject(400, 'invalid sessionId')

  const designOnly = body.designOnly === true
  const normalizedMode = mode as RunInput['mode']
  if (!isSupportedWorkflowIntent({ mode: normalizedMode, designOnly, deploy: body.deploy === true })) {
    return reject(
      400,
      'only read-only explore mode is currently enabled; development and deployment require a host-owned question/permission broker',
    )
  }
  return {
    ok: true,
    value: {
      repoPath: configuredRepo,
      requirement,
      module: body.module,
      mode: 'explore',
      deploy: false,
      designOnly: false,
      changeId: body.changeId as string | undefined,
      sessionId: typeof body.sessionId === 'string' ? body.sessionId.trim() : undefined,
    },
  }
}

export interface ValidGateBody {
  runId: string
  stepId: StepId
  action: 'confirm' | 'cancel' | 'revise'
  response?: string
  reviewedEvidenceIds?: string[]
}

export function validateGateBody(body: unknown): ValidationResult<ValidGateBody> {
  if (!isRecord(body)) return reject(400, 'JSON object body is required')
  if (!isSafeWorkflowId(body.runId)) return reject(400, 'invalid runId')
  if (typeof body.stepId !== 'string' || !STEP_IDS.has(body.stepId)) return reject(400, 'invalid stepId')
  if (body.action !== 'confirm' && body.action !== 'cancel' && body.action !== 'revise') {
    return reject(400, 'invalid gate action')
  }
  if (body.response !== undefined && typeof body.response !== 'string') return reject(400, 'invalid gate response')
  const response = typeof body.response === 'string' ? body.response.trim() : undefined
  if ((response?.length ?? 0) > MAX_RESPONSE_LENGTH) return reject(413, 'gate response is too large')
  if (body.stepId === 'requirement-clarify' && body.action === 'confirm' && (response ?? '') === '') {
    return reject(400, 'clarification response is required')
  }
  if (body.action === 'revise' && (body.stepId !== 'design-gate' || (response ?? '') === '')) {
    return reject(400, 'design revision instructions are required')
  }
  if (body.reviewedEvidenceIds !== undefined && (!Array.isArray(body.reviewedEvidenceIds)
    || body.reviewedEvidenceIds.length > 8
    || !body.reviewedEvidenceIds.every(id => typeof id === 'string' && /^ke-[0-9a-f]{24}$/.test(id)))) {
    return reject(400, 'invalid reviewed evidence ids')
  }
  return {
    ok: true,
    value: {
      runId: body.runId,
      stepId: body.stepId as StepId,
      action: body.action,
      ...(response === undefined || response === '' ? {} : { response }),
      ...(Array.isArray(body.reviewedEvidenceIds) ? { reviewedEvidenceIds: body.reviewedEvidenceIds as string[] } : {}),
    },
  }
}

function parseFields(response: string): ValidationResult<Record<string, string>> {
  if (typeof response !== 'string' || response.trim() === '') return reject(400, 'response is required')
  if (response.length > MAX_RESPONSE_LENGTH) return reject(413, 'response is too large')
  const fields: Record<string, string> = {}
  for (const rawLine of response.split(/\r?\n/)) {
    const line = rawLine.trim()
    if (line === '') continue
    const match = /^([a-z][a-z0-9-]{0,63})\s*[:=]\s*(.+)$/i.exec(line)
    if (match === null) return reject(400, `invalid field line: ${line.slice(0, 80)}`)
    const key = match[1]!.toLowerCase()
    if (Object.hasOwn(fields, key)) return reject(400, `duplicate field: ${key}`)
    fields[key] = match[2]!.trim()
  }
  return { ok: true, value: fields }
}

function requireFields(fields: Record<string, string>, required: readonly string[]): ValidationResult<Record<string, string>> {
  const missing = required.filter(key => fields[key] === undefined || fields[key] === '')
  return missing.length === 0 ? { ok: true, value: fields } : reject(400, `missing fields: ${missing.join(', ')}`)
}

export function validateDevelopInputs(response: string): ValidationResult<Record<string, string>> {
  const parsed = parseFields(response)
  if (!parsed.ok) return parsed
  const required = [
    'author', 'email', 'category', 'max-retries', 'build-mode',
    'bugzilla', 'cve', 'assisted-by', 'pre-review-strict',
  ] as const
  const complete = requireFields(parsed.value, required)
  if (!complete.ok) return complete
  const fields = complete.value
  if (fields.author!.length < 2
    || !/[\p{L}]/u.test(fields.author!)
    || /^(?:todo|tbd|unknown|anonymous|name|n\/a|na)$/i.test(fields.author!)) {
    return reject(400, 'author must be a real name')
  }
  if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(fields.email!)) return reject(400, 'invalid email')
  if (!new Set(['feature', 'bugfix', 'optimize', 'doc']).has(fields.category!)) return reject(400, 'invalid category')
  if (!/^\d+$/.test(fields['max-retries']!) || Number(fields['max-retries']) > 10) {
    return reject(400, 'max-retries must be an integer from 0 to 10')
  }
  if (!new Set(['fast', 'full-build']).has(fields['build-mode']!)) return reject(400, 'invalid build-mode')
  try {
    const url = new URL(fields.bugzilla!)
    if (url.protocol !== 'https:' && url.protocol !== 'http:') return reject(400, 'invalid bugzilla URL')
  } catch {
    return reject(400, 'invalid bugzilla URL')
  }
  if (!/^(?:NA|CVE-\d{4}-\d{4,})$/i.test(fields.cve!)) return reject(400, 'invalid cve')
  if (fields['assisted-by']!.length > 200) return reject(400, 'assisted-by is too long')
  if (!new Set(['true', 'false']).has(fields['pre-review-strict']!.toLowerCase())) {
    return reject(400, 'pre-review-strict must be true or false')
  }
  return { ok: true, value: fields }
}

export function validateRunIdBody(body: unknown): ValidationResult<{ runId: string }> {
  if (!isRecord(body) || !isSafeWorkflowId(body.runId)) return reject(400, 'invalid runId')
  return { ok: true, value: { runId: body.runId } }
}
